# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: leSecret
  expiration: 604800
  route:
    authentication:
      path: token
      refresh: refresh