# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 8080
# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: leSecret
  expiration: 604800
  route:
    authentication:
      path: token
      refresh: refresh

logging:
  level:
    root: INFO
    org.springframework: ERROR
    example: DEBUG
